# This is adapted from
# https://github.com/hvr/multi-ghc-travis

# Don't set language:haskell

env:
  - GHCVER=7.4.1
  - GHCVER=7.6.3

before_install:
  - travis_retry sudo apt-add-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-1.18 update
  - make
  - cabal-1.18 install --only-dependencies --enable-tests

script:
  - cabal-1.18 configure --enable-tests -v2
  - cabal-1.18 build
  - cabal-1.18 check
  - cabal-1.18 sdist
  - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
      cabal-1.18 install "$SRC_TGZ";
    else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
    fi
  - cd ../tests
  - cabal install

