# hpack package description.
# See
# https://github.com/sol/hpack
name: rainbow
synopsis: Print text to terminal with colors and effects
version: 0.28.0.4
license: BSD3
license-file: LICENSE
copyright: Copyright 2013-2018 Omari Norman
author: Omari Norman
maintainer: omari@smileystation.com
stability: Experimental
homepage: https://www.github.com/massysett/rainbow
bug-reports: https://www.github.com/massysett/rainbow/issues"
category: System

dependencies:
  - base >= 4.8 && < 5
  - text
  - bytestring
  - process
  - lens-simple

ghc-options: -Wall
other-extensions: TemplateHaskell
source-dirs: lib
github: massysett/rainbow

library: {}

tests:
  rainbow-instances:
    main: rainbow-instances.hs
    source-dirs: tests
    dependencies:
      - QuickCheck
  test8color:
    main: test8color.hs
    source-dirs: tests
  test256color:
    main: test256color.hs
    source-dirs: tests
  colorTest:
    main: colorTest.hs
    source-dirs: tests

